# Generated by Django 4.2.3 on 2023-08-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='platform',
            field=models.CharField(choices=[('DT', 'Desktop'), ('ML', 'Mobile')], default='DT', max_length=2),
        ),
    ]
